ALTER TABLE workflows ADD COLUMN IF NOT EXISTS state JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
ALTER TABLE answers ADD COLUMN IF NOT EXISTS source_comment_id TEXT;
